### ISSUE TITLE
issue: EBLoader.js needs to be on the root

### ISSUE THREAD

**Issue by adam-hite** [pyramidium/generator-bannertime#115] opened 2018-03-06 22:21 UTC
According to Sizmek's [documentation](https://support.sizmek.com/hc/en-us/articles/200722459-HTML5-Workspaces):
![2](https://user-images.githubusercontent.com/9426691/37061840-5377ef9e-215a-11e8-8058-7cfd3bc6ea3b.png)

It currently lives in the js folder.

I'm getting this error in Sizmek:
![1](https://user-images.githubusercontent.com/9426691/37061839-5364aba0-215a-11e8-9c2d-9dd20021f5be.png)

**Comment by joemidi** [comment] 2018-03-06 22:39
Hey @adam-hite 

I think you may simply need to add the script tag to the `index.html`

```
<script src="js/EBLoader.js" type="text/javascript"></script>
```

From there it should pick it up.

-------
Tested on generator version 3.0.2 using the following:
```
$ yo bannertime:new
>
? Set the width of the banner: 300
? Set the height of the banner: 600
? What is the name of the new format? (kebab-case) sizmek-test-300x600
? What type of banner is it? Sizmek
```

**Comment by adam-hite** [comment] 2018-03-07 15:43
Sizmek wants the file to be in the root, not in the js folder. The script tag is pointing to the js folder.

**Comment by joemidi** [comment] 2018-03-08 09:32
I've just tested a fresh campaign with 3.0.2 using these files: [sizmek-test-300x250.zip](https://github.com/bannertime/generator-bannertime/files/1792508/sizmek-test-300x250.zip)

![screen shot 2018-03-08 at 09 24 14](https://user-images.githubusercontent.com/2073312/37143286-9d7ecc1c-22b2-11e8-87ae-d83ce704c1df.png)

From what I can tell it works fine with the `EBLoader.js` sitting in the `/js` folder and the script tag as:
```
<script src="js/EBLoader.js" type="text/javascript"></script>
```

I would also note that the error message in your second image explicitly says within the _root HTML_ file rather than the _root folder/workspace_: `The include of the adkit.js or EBLoader.js is missing in the root HTML file.`

**Comment by danielhauchler** [comment] 2018-03-08 09:38
You can also use:
      
     <script src="./EBLoader.js" type="text/javascript"></script>

**Comment by joemidi** [comment] 2018-03-08 09:40
@danielhauchler Sure, it doesn't really matter where you put the file, as long as you reference it with a script tag in the root HTML file.

We've just placed it inside the `/js` folder so that it structurally makes sense.

**Comment by joemidi** [comment] 2018-06-26 10:12
Closing this as it works as intended.

**Closed as completed by joemidi** 2018-06-26 10:12 UTC
