### ISSUE TITLE
feat: spritesheets

### ISSUE THREAD

**Issue by barrypollinate** [pyramidium/generator-bannertime#13] opened 2015-11-23 17:53 UTC
Spritesheet generation would be a great feature to add. Perhaps gulp.spritesmith?

**Comment by pyramidium** [comment] 2015-11-23 17:59
How odd I created an issue at exactly the same time as you #12. Great idea. I have implemented this in the past using gulp-spritesmith so it should be pretty straight-forward.

**Comment by joemidi** [comment] 2015-11-23 18:00
Duplicate of #12

**Closed as completed by joemidi** 2015-11-23 18:00 UTC
Labels: duplicate

**Comment by barrypollinate** [comment] 2015-11-23 18:01
I got the notification that you created this literally at the same moment I posted.. ha!

**Comment by pyramidium** [comment] 2015-11-23 18:02
:+1:
